Algoritmo "entrada_de_dados"

Var

   idade : inteiro
   salario1, salario2 : real
   nome : caractere

Inicio

   escreva("Digite seu nome: ")
   leia(nome)

   escreva("Digite sua idade: ")
   leia(idade)

   escreval("Digite quanto voce ganhou nos ultimos dois meses: ")
   leia (salario1)
   leia (salario2)

   escreval("Dados Digitados:")
   escreval("Nome = ", nome)
   escreval("Idade", idade)
   escreval("salario1 =", salario1:8:2)
   escreval("salario2 =", salario2:8:2)

Fimalgoritmo